version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: >
      bash -c "python3 stripe_server/manage.py migrate 
      && python3 stripe_server/manage.py loaddata stripe_server/test.json 
      && python3 stripe_server/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
